### PR TITLE
Kill.Killer may be nil, "worldspawn" Equipment should be EqWorld

### LINKED ISSUE #156: Kill.Killer may be nil
**Describe the bug**
The Killer pointer in the events.Kill type may be nil. In my case, the player fell to his death.
Similar to #151 .

**To Reproduce**
[Link to demo](https://user.informatik.uni-goettingen.de/~linus.weber/s11_severity_de_inferno.dem)

Code:
[Line in parser code](https://github.com/markus-wa/demoinfocs-golang/blob/d7347829b857e430b495788927511915076081ea/game_events.go#L279)

```go
type Kill struct {
	KillerName string
	KillerTeam common.Team
	VictimName string
	VictimTeam common.Team
	Weapon     string
}

parser.RegisterEventHandler(func(e event.Kill) {	
	kill := ocom.Kill{
		KillerName: e.Killer.Name,
		KillerTeam: e.Killer.Team,
		VictimName: e.Victim.Name,
		VictimTeam: e.Victim.Team,
		Weapon:     e.Weapon.Weapon.String(),
}
```

**Expected behavior**
`Kill.Killer` should be the same as `Kill.Victim`. Also, the `Kill.Weapon` could be something like suicide or falling instead of `UNKNOWN`. Maybe don't dispatch a Kill event at all or add a comment in the documentation.

**Library version**
v1.3.3

### PR DESCRIPTION
**Pull request by markus-wa**
fixes #156

### CODE REVIEW

**Comment by markus-wa** [comment]
cc @Linus4 - please verify

**Comment by markus-wa** [comment]
Added docs for `WeaponFire.Shooter` and adjusted docs for `Kill.Killer`

**Comment by markus-wa** [comment]
Shall we merge this @Linus4?

**Comment by Linus4** [comment]
Looks good to me. 👍 (Didn't look at this PR but only at the issue, so I missed it until now 👀 )

**Comment by markus-wa** [comment]
thanks! merged 🙂

**Pull request merged**
