### PR TITLE
game_events: dispatch MatchStartedEvent on round_announce_match_start

### PR DESCRIPTION
**Pull request by micvbang**

### CODE REVIEW

**Comment by markus-wa** [comment]
Interesting find - but Travis doesn't look too happy about this.

It would change when and how often this event is emitted for some demos so I'm not sure this is the right solution. In the failed test you can see that there are no players after the event is sent out in one case.

Maybe a new event is needed here. Perhaps just some kind of generic event that is dispatched for all unhandled events?
That would leave it up to the higher level application to decide what to do in such situations.

Here's how the test demos in the test set behave regarding `begin_new_match` & `round_announce_match_start`:
```
$ go test -tags debugdemoinfocs -run TestDemoSet | grep -P "Parsing|round_announce_match_start|begin_new_match"
Parsing 'test/cs-demos/set/2013-03-29-CPHGames-natus-vincere-fnatic-de_train_se.dem'
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
Parsing 'test/cs-demos/set/2013-11-28-DHW2013-nip-vs-lgb-train.dem'
GameEvent: begin_new_match Data: map[]
Parsing 'test/cs-demos/set/2014-11-01-ESWC2014-hellraisers-vs-fnatic-de_nuke.dem'
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
Parsing 'test/cs-demos/set/2015-01-23-MLGXGAMES2015-Groups-clg-vs-ldlc-dust2.dem'
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
Parsing 'test/cs-demos/set/2015-08-23-ESLOneCologne2015-fnatic-vs-virtuspro-mirage.dem'
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
Parsing 'test/cs-demos/set/2015-11-01-DHOpenClujNappoca2015-EnVy-vs-NaVi-train.dem'
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
Parsing 'test/cs-demos/set/2016-11-30-ELEAGUESeason2-dignitas-vs-sk-dust2.dem'
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
Parsing 'test/cs-demos/set/2017-03-27-DHOpenAustin2017NAQuali-clg-vs-luminosity-cobblestone.dem'
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
Parsing 'test/cs-demos/set/2017-05-17-ECSSeason3NA-liquid-vs-renegades-cobblestone.dem'
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
Parsing 'test/cs-demos/set/2017-05-17-ESLProLeagueS5Relegation-penta-vs-virtuspro-inferno.dem'
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
Parsing 'test/cs-demos/set/2017-05-20-ESLOneCologneEUClosedQualifier-dignitas-vs-k29-map2-mirage.dem'
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
Parsing 'test/cs-demos/set/2018-05-10-ECSSeason5EU-astralis-vs-gambit-overpass.dem'
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
GameEvent: begin_new_match Data: map[]
GameEvent: round_announce_match_start Data: map[]
```

**Comment by micvbang** [comment]
Yeah, I think you are right that it should be treated as a separate event.

I'll try and play around with it when I get the time :)

**Comment by markus-wa** [comment]
There is now a `GenericGameEvent` in `v0.5.0`.

You could use:
```go
p.RegisterEventHandler(func(e events.GenericGameEvent) {
	if e.Name == "round_announce_match_start" {
		// Your code here
	}
})
```

If you prefer to have a separate event instead you can still add it though.

**Comment by micvbang** [comment]
Cool! That's a reasonable solution that allows yet-unhandled events to be handled in the future!

**Pull request closed without merging**
