### PR TITLE
Revert to use entity id instead of entity

### PR DESCRIPTION
**Pull request by zyphie**
The solution with using the entity doesn't really work. For some nades (e.g. molotov), the entity is deleted. If we have the ID, while we cannot access the entity, we can at least relate the different events (throw, explode, expire).

### CODE REVIEW

**Comment by markus-wa** [comment]
I wonder why we're so quick to destroy unused entities then.
Maybe this could be solved by not destroying the entity instead?

I'll look into it a bit more later, if not, this looks like the next best thing.

**Comment by zyphie** [comment]
Entity IDs are not unique throughout a demo, though. I.e. multiple entities (that does not exist at the same time) can have the same ID. Wouldn't this pose a problem if we persist the entities?

**Comment by markus-wa** [comment]
Good point, guess this'll have to do

**Comment by markus-wa** [comment]
Could you rename it to `NadeEntityID` again tho? :)

**Pull request merged**
