### PR TITLE
Issue 38 - Entity.Position() for CCSPlayer entities

### PR DESCRIPTION
**Pull request by markus-wa**
See #38 

Cc @micvbang can you verify this works. I remember you originally bringing this up via Gitter.

### CODE REVIEW

**Comment by micvbang** [comment]
I'm unavailable to verify this right now. Will look at it next week :slightly_smiling_face:

**Comment by micvbang** [comment]
Just tested this, and it looks good.

Sorry that this took a while to confirm!

**Comment by markus-wa** [comment]
Thanks! and no problem.

**Comment by micvbang** [comment]
I just realized that there is a quite substantial performance degradation when using this commit.

I haven't looked into what is causing the update yet, but if I find out, I'll report ASAP

**Comment by markus-wa** [comment]
Wow that's pretty bad. I'll look into it this evening as well.

**Comment by markus-wa** [comment]
Can't reproduce this right now

With 95349a9:
```
mwalt@DESKTOP-5DQ62Q0 MINGW64 ~/go/src/github.com/markus-wa/demoinfocs-golang (master)
$ go test -run _NONE_ -bench .
goos: windows
goarch: amd64
pkg: github.com/markus-wa/demoinfocs-golang
BenchmarkDemoInfoCs-8                  1        1552202100 ns/op
BenchmarkInMemory-8                    1        1557548800 ns/op
BenchmarkConcurrent-8                  1        1818294500 ns/op
--- BENCH: BenchmarkConcurrent-8
    demoinfocs_test.go:438: Running concurrency benchmark with 2 demos
PASS
ok      github.com/markus-wa/demoinfocs-golang  5.324s
````


With 4b006c8:
``` 
mwalt@DESKTOP-5DQ62Q0 MINGW64 ~/go/src/github.com/markus-wa/demoinfocs-golang (master)
$ go test -run _NONE_ -bench .
goos: windows
goarch: amd64
pkg: github.com/markus-wa/demoinfocs-golang
BenchmarkDemoInfoCs-8                  1        1514316800 ns/op
BenchmarkInMemory-8                    1        1504429400 ns/op
BenchmarkConcurrent-8                  1        1797764000 ns/op
--- BENCH: BenchmarkConcurrent-8
    demoinfocs_test.go:438: Running concurrency benchmark with 2 demos
PASS
ok      github.com/markus-wa/demoinfocs-golang  5.214s
```

**Comment by markus-wa** [comment]
Is it just in your code? Do you use a lot of positions?

If so with or without binding?

**Comment by micvbang** [comment]
Yeah, sorry, it's with the event handlers that I registered. I do use a lot of positions - I run through participating players in the game state at 21 frames per second on a 128 frame demo. No binding :slightly_smiling_face: 

It's on Ubuntu 16.04 and 17.04

**Comment by markus-wa** [comment]
Can you past the code that does all the position stuff?

**Comment by markus-wa** [comment]
Sorry, my bad.

I was using the master, to which I backported the change. However, there it works because the library doesn't have `BindPosition()` which is used on the v1 to track player positions.

We're calling `Entity.FindProperty()` twice every time the positions update, which turns out to be fairly expensive:

image


```
     10ms       10ms    198:func (e *Entity) positionPlayer() r3.Vector {
     110ms     42.73s    199:   xy := e.FindProperty(propVecOriginPlayerXY).value.VectorVal
      10ms     35.67s    200:   z := float64(e.FindProperty(propVecOriginPlayerZ).value.FloatVal)
      90ms       90ms    201:   return r3.Vector{
         .          .    202:           X: xy.X,
         .          .    203:           Y: xy.Y,
         .          .    204:           Z: z,
         .          .    205:   }
         .          .    206:}
```

I'll see if this can be worked around (e.g. by caching the relevant properties). Worst case `BindPosition()` might need to be removed.

**Pull request merged**
