### PR TITLE
common: add new ammo functions to Equipment for grenades

### LINKED ISSUE #145: Grenades: AmmoInMagazine and AmmoReserve always -1 / 0
**Describe the bug**

The `AmmoInMagazine` and `AmmoReserve` fields of the `Equipment` type always have the following values for *any grenade*, regardless of how many instances of the grenade the player actually owns. This is a problem because there is no way to tell how many flashbangs a player owns.

```
AmmoInMagazine: -1
AmmoReserve: 0
```

**To Reproduce**

Any demo I've tested so far.
https://www.hltv.org/download/demo/51879

Code:

```go
sort.Slice(weapons, func(i, j int) bool { return weapons[i].Weapon < weapons[j].Weapon })
for _, w := range weapons {
	if w.Class() == common.EqClassGrenade {
		switch w.Weapon {
		case common.EqFlash:
			// there seems to be only one flashbang in player.Weapons() even if he has two
			fmt.Println("AmmoInMagazine:", w.AmmoInMagazine)
			fmt.Println("AmmoReserve:", w.AmmoReserve)
	}
}
```

**Expected behavior**

`AmmoInMagazine` should be 1 and `AmmoReserve` should be the number of grenades the player owns of this type in addition to that.

**Library version**

v1.3.1

**Additional context**

/

### PR DESCRIPTION
**Pull request by markus-wa**
fixes #145

- AmmoInMagazine2() returns 1 for grenades
- AmmoReserve2() returns 'Owner.LeftAmmo[AmmoType] - 1' for grenades

This means if a player has two flashbangs:
- `AmmoInMagazine2()` will return 1
- `AmmoInReserve2()` will return 1
- total amount of flashbangs (2) = `AmmoInMagazine2() + AmmoInReserve2()`

### CODE REVIEW

**Comment by markus-wa** [comment]
@Linus4 @BestAwperEver @xXxhaxmeister42xXx could you guys please test & review this PR for #145 if you have some time?

Also I'm not 100% sure if `AmmoReserve2()` returning `1` when the player has `2` flashbangs is completely logical but I think it's better this way.

**Comment by markus-wa** [comment]
Alright, thanks @BestAwperEver !

I also managed to download the demo yesterday evening (to my mobile 😄)

But I'd say let's take the M4 ammo discussion to #149, this PR is big enough 🙂

**Comment by xXxhaxmeister42xXx** [comment]
I didn't do in-depth testing, but from what i did i can support bestawpers findings that the spare grenades work correctly.

```AmmoReserve2()``` can occasionally be -1. (Perhaps right after a grenade has been thrown?)

Note that you wrote Ammo**In**Reserve2 instead of AmmoReserve2 in the top comment example.

**Comment by markus-wa** [comment]
> AmmoReserve2() can occasionally be -1. (Perhaps right after a grenade has been thrown?)

strange ... might have to look into that

> Note that you wrote AmmoInReserve2 instead of AmmoReserve2 in the top comment example.

fixed, cheers!

**Pull request merged**
