### PR TITLE
fix array decoding

### PR DESCRIPTION
**Pull request by markus-wa**
see #509

I'm not really sure why the old version was crashing on all versions of Go except 1.21 - but this should fix array decoding to be much more consistent.

Previously PropertyUpdate events contained either a `fieldState` or an int, now it's always an array.

### CODE REVIEW

**Comment by BestAwperEver** [comment]
It still fails for me, but now at least I can create a replicable example ([here's the match](https://www.faceit.com/en/csgo/room/1-f06e69ac-25e4-4a11-a7ec-092bdf1c4f69)):
```go
package main

import (
	dem "github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs"
	"github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/events"
	"log"
	"os"
)

func main() {
	f, err := os.Open("1-f06e69ac-25e4-4a11-a7ec-092bdf1c4f69-1-1.dem")

	if err != nil {
		log.Panic("failed to open demo file: ", err)
	}
	defer f.Close()

	p := dem.NewParser(f)
	defer p.Close()

	p.RegisterEventHandler(func(e events.FrameDone) {
		for _, pl := range p.GameState().Participants().All() {
			pl.MVPs()
		}
	})

	err = p.ParseToEnd()
	if err != nil {
		panic(err)
	}
}
```
`panic: interface conversion: interface {} is nil, not int32` at `pkg/demoinfocs/sendtables/propdecoder.go:137`

**Comment by markus-wa** [comment]
can you send the full stacktrace please @BestAwperEver 🙏

**Comment by BestAwperEver** [comment]
Sure! Is it still non-replicable though?
```
panic: interface conversion: interface {} is nil, not int32
stacktrace:
goroutine 18 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.NewParserWithConfig.func1({0x1008f10e0, 0x14000a3c690})
        /Users/mshirobokov/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.3-0.20240215151838-f39979ec2282/pkg/demoinfocs/parser.go:403 +0x2c
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
        /Users/mshirobokov/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x48
panic({0x1008f10e0?, 0x14000a3c690?})
        /usr/local/go/src/runtime/panic.go:914 +0x218
github.com/markus-wa/godispatch.callConsumerCode.func1()
        /Users/mshirobokov/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x60
panic({0x1008f10e0?, 0x14000a3c680?})
        /usr/local/go/src/runtime/panic.go:914 +0x218
github.com/markus-wa/godispatch.callConsumerCode.func1()
        /Users/mshirobokov/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x60
panic({0x1008c9ea0?, 0x14001186ff0?})
        /usr/local/go/src/runtime/panic.go:914 +0x218
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables.PropertyValue.Int(...)
        /Users/mshirobokov/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.3-0.20240215151838-f39979ec2282/pkg/demoinfocs/sendtables/propdecoder.go:137
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/common.getInt(...)
        /Users/mshirobokov/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.3-0.20240215151838-f39979ec2282/pkg/demoinfocs/common/entity_util.go:10
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/common.(*Player).MVPs(0x14000583380)
        /Users/mshirobokov/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.3-0.20240215151838-f39979ec2282/pkg/demoinfocs/common/player.go:746 +0x270
main.main.func1({})
        /Users/mshirobokov/GolandProjects/cs2-test0/main.go:23 +0x60
reflect.Value.call({0x10088a8e0?, 0x1400019c408?, 0x14000a8d528?}, {0x1007eae97, 0x4}, {0x14000a8d630, 0x1, 0x1008e9de0?})
        /usr/local/go/src/reflect/value.go:596 +0x994
reflect.Value.Call({0x10088a8e0?, 0x1400019c408?, 0x14000b95b00?}, {0x14000a8d630?, 0xf700014000a8d618?, 0x0?})
        /usr/local/go/src/reflect/value.go:380 +0x94
github.com/markus-wa/godispatch.callConsumerCode({0x10088a8e0?, 0x1400019c408?, 0x14000a8d5f8?}, {0x14000a8d630?, 0x140002fe700?, 0x0?})
        /Users/mshirobokov/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x44
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0x14000184300, {0x1008c09a0, 0x100de32a0})
        /Users/mshirobokov/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1fc
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).handleFrameParsed(0x140002fe700, 0x0)
        /Users/mshirobokov/go/pkg/mod/github.com/markus-wa/demoinfocs-golang/v4@v4.0.3-0.20240215151838-f39979ec2282/pkg/demoinfocs/parsing.go:527 +0x48
reflect.Value.call({0x10088b460?, 0x14000198ab0?, 0x14000a8ddd8?}, {0x1007eae97, 0x4}, {0x14000a8dee0, 0x1, 0x0?})
        /usr/local/go/src/reflect/value.go:596 +0x994
reflect.Value.Call({0x10088b460?, 0x14000198ab0?, 0x0?}, {0x14000a8dee0?, 0xdc00000000000000?, 0x0?})
        /usr/local/go/src/reflect/value.go:380 +0x94
github.com/markus-wa/godispatch.callConsumerCode({0x10088b460?, 0x14000198ab0?, 0x14000a8de98?}, {0x14000a8dee0?, 0x14000100000?, 0x10050c4c4?})
        /Users/mshirobokov/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x44
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0x140001842a0, {0x100876e20, 0x100de32a0})
        /Users/mshirobokov/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1fc
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0x140001842b8?, {0x100876e20?, 0x100de32a0?})
        /Users/mshirobokov/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x50
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0x140001842a0, 0x0?)
        /Users/mshirobokov/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xcc
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues in goroutine 1
        /Users/mshirobokov/go/pkg/mod/github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x1ac


goroutine 1 [running]:
main.main()
        /Users/mshirobokov/GolandProjects/cs2-test0/main.go:29 +0x1fc

Process finished with the exit code 2
```

**Comment by markus-wa** [comment]
@BestAwperEver that's a CS:GO demo, right?

**Comment by markus-wa** [comment]
@BestAwperEver can you try again with `go get github.com/markus-wa/demoinfocs-golang/v4/pkg/demosinfocs@5d503e7f3df1fb5b207777c6810d72fafc1ed1c7`

**Comment by BestAwperEver** [comment]
I assume you've already tested it, but I ran the demo on the current master and encountered no issues with the code above. Thanks!

**Pull request merged**
