### PR TITLE
Parser: Refactor event handling

### PR DESCRIPTION
**Pull request by markus-wa**
Clean up the mess that is `Parser.handleGameEvent()`

### CODE REVIEW

**Comment by markus-wa** [comment]
@micvbang if you could review this that would be amazing 😄

**Comment by micvbang** [comment]
Yes, sir! I've put it on my TODO for this week :)

**Comment by markus-wa** [comment]
Just noticed there's a [failing Travis job](https://travis-ci.org/markus-wa/demoinfocs-golang/jobs/503844244#L560) here, smells like a flaky test. Will have to investigate further.

**Comment by markus-wa** [comment]
> Just noticed there's a failing Travis job here, smells like a flaky test. Will have to investigate further.

fixed in master at cef132c0e2da16a7758f43cda58efd8d4c80bb8b

**Pull request merged**
