### PR TITLE
README: add 'Projects using demoinfocs-golang' section

### PR DESCRIPTION
**Pull request by markus-wa**
@micvbang is it ok for you if we add this?

If so, would you like to have a short (one sentence) description for noesis.gg?

e.g.

## Projects using demoinfocs-golang

- [noesis.gg](https://www.noesis.gg/) - Lorem ipsum ...

### CODE REVIEW

**Comment by markus-wa** [comment]
Ping @micvbang

**Comment by micvbang** [comment]
Yes, definitely! Sorry, I totally missed this the first time around

**Comment by markus-wa** [comment]
Could you give your own short (one sentence) description of the site to put next to the link?

>FYI: In order to allow for more agility for us internally, we're currently working on a forked version. We, of course, intend to continue to contribute changes that make sense back!

Sounds good!

**Comment by micvbang** [comment]
Let's try "A suite of explorative tools to help you analyze and improve your CS:GO performance" :)

**Comment by micvbang** [comment]
Thank you! :grin:

**Pull request merged**
