### PR TITLE
Added de_ancient support

### PR DESCRIPTION
**Pull request by srjnm**

### CODE REVIEW

**Comment by markus-wa** [comment]
thanks for the PR @srjnm 

are you sure those translations are right?

I just recorded a demo locally and ran `go run heatmap.go -demo path/to/dem` and it gave me this:

out_comments

the red arrows and ellipse show what the translations output (small yellowish/orange dots). the big red dots show where these should have been.

this is the demo I used:
[ancient.zip](https://github.com/markus-wa/demoinfocs-golang/files/6677720/ancient.zip)

**Comment by srjnm** [comment]
i got the translations from this map file - 
[de_ancient.txt](https://github.com/markus-wa/demoinfocs-golang/files/6677781/de_ancient.txt)
the outputs from my project turned out fine -
electronic_ancient

**Comment by srjnm** [comment]
i ran this [demo file](https://drive.google.com/file/d/19DgALLPVG3eyENWfeFa6X-DNpp1J_i9l/view?usp=sharing) with heatmap.go and got this-
hm

**Comment by markus-wa** [comment]
thanks for the  additional details, I just did another more thorough test and it looked a bit better - I'll have a final look in a bit - I wonder what happened to my demo there ...

**Comment by srjnm** [comment]
yeah, not sure what was off. i recorded a [demo](https://github.com/markus-wa/demoinfocs-golang/files/6678064/ancient_srjnm.zip) myself and ran heatmap.go just to be sure-
hm-ancient

**Comment by markus-wa** [comment]
btw, I had absolutely no idea that csgo shipped those translations in these .txt files, thanks for letting me know!

**Comment by markus-wa** [comment]
merged :)

**Comment by srjnm** [comment]
> btw, I had absolutely no idea that csgo shipped those translations in these .txt files, thanks for letting me know!

glad I could help. I found it [here](https://github.com/CSGO-Analysis/csgo-maps-overviews/tree/master/overviews) while browsing through the maps to find ancient.

thanks for the merge!

**Pull request merged**
